// src/components/MenuCategories/MenuCategories.svelte
<div class="categoryList">
	<a href="/blog?cat=thai" class="categoryItem style">Thai</a>
	<a href="/blog?cat=japanese" class="categoryItem fashion">Japanese</a>
	<a href="/blog?cat=italian" class="categoryItem food">Italian</a>
	<a href="/blog?cat=indian" class="categoryItem travel">Indian</a>
	<a href="/blog?cat=spanish" class="categoryItem culture">Spanish</a>
	<a href="/blog?cat=chinese" class="categoryItem coding">Chinese</a>
</div>

<style lang="postcss">
	.categoryList {
		@apply flex flex-wrap gap-3;
	}

	.categoryItem {
		@apply rounded-lg px-4 py-2 text-sm;
	}

	.style {
		@apply bg-blue-100 text-blue-600;
	}

	.fashion {
		@apply bg-rose-100 text-rose-600;
	}

	.food {
		@apply bg-green-100 text-green-600;
	}

	.travel {
		@apply bg-orange-100 text-orange-600;
	}

	.culture {
		@apply bg-purple-100 text-purple-600;
	}

	.coding {
		@apply bg-indigo-100 text-indigo-600;
	}
</style>

// app/Components/MenuCategories/MenuCategories.tsx
import Link from "next/link";
import React from "react";
import styles from "./MenuCategories.module.css";

const MenuCategories = () => {
  return (
    <div className={styles.categoryList}>
      <Link
        href="/blog?cat=style"
        className={`${styles.categoryItem} ${styles.style}`}
      >
        Thai
      </Link>
      <Link href="/blog" className={`${styles.categoryItem} ${styles.fashion}`}>
        Japanese
      </Link>
      <Link href="/blog" className={`${styles.categoryItem} ${styles.food}`}>
        Italian
      </Link>
      <Link href="/blog" className={`${styles.categoryItem} ${styles.travel}`}>
        Indian
      </Link>
      <Link href="/blog" className={`${styles.categoryItem} ${styles.culture}`}>
        Spanish
      </Link>
      <Link href="/blog" className={`${styles.categoryItem} ${styles.coding}`}>
        Chinese
      </Link>
    </div>
  );
};

export default MenuCategories;
