// app/Components/Comments/Comments.tsx
import React from "react";
import style from "./Comments.module.css";
import Link from "next/link";
import Image from "next/image";

const Comments = () => {
  const status = true;

  return (
    <>
      <div className={style.container}>
        <div className={style.title}>Comments</div>
        {status === true ? (
          <div className={style.write}>
            <textarea
              placeholder="Write a Comment..."
              className={style.input}
            ></textarea>
            <button className={style.button}> Send </button>
          </div>
        ) : (
          <Link href="/Login">Please Login to Write a comment</Link>
        )}

        <div className={style.comments}>
          <div className={style.comment}>
            <div className={style.user}>
              <div className={style.Cimage}>
                <Image
                  src="/Food.jpg"
                  alt="user Image"
                  fill
                  className={style.image}
                />
              </div>
              <div className={style.stylearound}>
                <div className={style.userInfo}>
                  <span className={style.username}>Megumi Fusigouro</span>
                  <span className={style.date}>10.02.2023</span>
                </div>
                <p className={style.desc}>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit.
                  Corrupti, molestiae optio odio dolorum recusandae
                  perspiciatis.
                </p>
              </div>
            </div>
          </div>
          <div className={style.comment}>
            <div className={style.user}>
              <div className={style.Cimage}>
                <Image
                  src="/Food.jpg"
                  alt="user Image"
                  fill
                  className={style.image}
                />
              </div>
              <div className={style.stylearound}>
                <div className={style.userInfo}>
                  <span className={style.username}>Megumi Fusigouro</span>
                  <span className={style.date}>10.02.2023</span>
                </div>
                <p className={style.desc}>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit.
                  Corrupti, molestiae optio odio dolorum recusandae
                  perspiciatis.
                </p>
              </div>
            </div>
          </div>
          <div className={style.comment}>
            <div className={style.user}>
              <div className={style.Cimage}>
                <Image
                  src="/Food.jpg"
                  alt="user Image"
                  fill
                  className={style.image}
                />
              </div>
              <div className={style.stylearound}>
                <div className={style.userInfo}>
                  <span className={style.username}>Megumi Fusigouro</span>
                  <span className={style.date}>10.02.2023</span>
                </div>
                <p className={style.desc}>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit.
                  Corrupti, molestiae optio odio dolorum recusandae
                  perspiciatis.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Comments;

// src/components/Comments/Comments.svelte
<script lang="ts">
	let status = true; 
</script>

<div class="container">
	<h1 class="title">Comments</h1>
	{#if status}
		<div class="write">
			<textarea placeholder="Write a Comment..." class="input" ></textarea>
			<button class="button">Send</button>
		</div>
	{:else}
		<a href="/login">Please Login to Write a comment</a>
	{/if}

	<div class="comments">
		{#each Array(3) as _}
			<div class="comment">
				<div class="user">
					<div class="userImageContainer">
						<img src="/Food.jpg" alt="user Image" class="image" />
					</div>
					<div class="userInfo">
						<span class="username">Megumi Fushiguro</span>
						<span class="date">10.02.2023</span>
					</div>
				</div>
				<p class="desc">
					Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti, molestiae optio odio
					dolorum recusandae perspiciatis.
				</p>
			</div>
		{/each}
	</div>
</div>

<style lang="postcss">
	.container {
		@apply mt-12;
	}

	.title {
		@apply mb-6 text-2xl font-bold text-gray-800;
	}

	.write {
		@apply flex flex-col gap-4;
	}

	.input {
		@apply w-full rounded-md border p-5;
	}

	.button {
		@apply w-max rounded-md bg-blue-500 px-4 py-2 text-white transition-colors hover:bg-blue-600;
	}

	.comments {
		@apply mt-8;
	}

	.comment {
		@apply mb-8;
	}

	.user {
		@apply mb-4 flex items-center gap-4;
	}

	.userImageContainer {
		@apply relative h-12 w-12;
	}

	.image {
		@apply h-full w-full rounded-full object-cover;
	}

	.userInfo {
		@apply flex flex-col;
	}

	.username {
		@apply font-medium;
	}

	.date {
		@apply text-sm text-gray-500;
	}

	.desc {
		@apply leading-6 text-gray-700;
	}
</style>
